-------------------------------------------------------------------------------
-- HALE Orbital Mechanics - Python Oracle Cross-Validation Suite
-------------------------------------------------------------------------------
-- Parses the committed reference CSVs under validation/data/ (generated by
-- validation/generate_reference.py from the independent NumPy/SciPy CR3BP
-- oracle) and re-derives the same quantities with the Ada implementation:
-- Lagrange points, Jacobi constants, trajectory endpoints (adaptive RK45),
-- and Floquet multipliers of an L1 Lyapunov orbit.
--
-- Run from the repository root (CI does); the suite reports a clear failure
-- if the reference data is missing.
-------------------------------------------------------------------------------

package Hale_Tests.Oracle is

   procedure Run_All_Oracle_Tests;

end Hale_Tests.Oracle;
