#!/usr/bin/env python3
"""
Cross-validation reference data generator for the HALE orbital mechanics library.

Generates CSV reference data in validation/data/ from the Python CR3BP oracle
(python/three-body-extension). The Ada library parses these CSVs and compares
its own results (Lagrange points, Jacobi constants, trajectory endpoints,
Floquet/monodromy eigenvalues) against them within documented tolerances.

Files produced
--------------
lagrange_points.csv
    L1..L5 normalized (x, y) positions and Jacobi constant for every
    predefined system in threebody.systems.SYSTEMS.
trajectories.csv
    Endpoint states after propagating four well-conditioned Earth-Moon
    initial conditions with the oracle's adaptive RK45 (rtol=atol=1e-12)
    for t = 2.0 normalized time units, plus the maximum Jacobi drift.
floquet.csv
    A planar Lyapunov orbit about Earth-Moon L1 (initial state, period)
    and the 6 monodromy-matrix eigenvalues sorted by |lambda| descending.

Usage
-----
    python3 validation/generate_reference.py          # (re)write validation/data/
    python3 validation/generate_reference.py --check  # CI drift gate: regenerate
                                                      # in memory, compare against
                                                      # committed CSVs, exit 0/1

Reproducibility
---------------
Headers carry the generator name and numpy/scipy versions only -- no dates or
timestamps. Regeneration is bit-identical on the same machine with the pinned
environment (python/three-body-extension/constraints.txt). Across differing
CPU/BLAS builds, eigenvalues of the monodromy matrix may vary more than the
base tolerance (the trivial unit pair is a defective 2x2 Jordan block and
splits at ~sqrt(perturbation)), so eigenvalue columns use a documented looser
tolerance in --check mode.
"""

# ruff: noqa: E402  (oracle imports must follow the sys.path bootstrap below)

import argparse
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]
ORACLE_SRC = REPO_ROOT / "python" / "three-body-extension" / "src"
sys.path.insert(0, str(ORACLE_SRC))

import numpy as np
import scipy

from threebody.constants import MU_EARTH_MOON
from threebody.cr3bp import jacobi_constant
from threebody.integrators import propagate, propagate_with_events
from threebody.lagrange import (
    lagrange_point_jacobi_constants,
    lagrange_point_L1,
    lagrange_points,
    linearized_dynamics_at_lagrange,
)
from threebody.periodic import PeriodicOrbit, differential_correction_planar
from threebody.stability import compute_monodromy_matrix
from threebody.systems import SYSTEMS

DATA_DIR = Path(__file__).resolve().parent / "data"

GENERATOR_NAME = "validation/generate_reference.py"

# --check tolerances (see module docstring).
REL_TOL = 1e-12
ABS_FLOOR = 1e-14
# Monodromy eigenvalue columns: the trivial unit pair is a defective Jordan
# block, so eigensolvers split it at ~sqrt(backward error) ~ 1e-6.  Base
# tolerances are unachievable across BLAS builds for those components.
EV_REL_TOL = 1e-9
EV_ABS_FLOOR = 1e-5
# Integrated trajectory endpoints: solve_ivp step-size decisions differ in
# the last ulp across Python/BLAS builds, and the arcs amplify that (the
# unstable L1 case by ~2 orders of magnitude over t=2).  Observed
# cross-runner endpoint deltas are ~2e-11 relative; 1e-9 keeps three orders
# of margin below anything the Ada-side comparison (1e-4) could feel.
TRAJ_REL_TOL = 1e-9
TRAJ_ABS_FLOOR = 1e-12
# jacobi_drift is itself integration noise (~1e-11); comparing it tightly
# is meaningless — only its order of magnitude matters.
DRIFT_ABS_FLOOR = 1e-10

# Lyapunov orbit configuration (Earth-Moon L1, x-amplitude toward Earth).
LYAPUNOV_AX = 0.02
TRAJECTORY_T_FINAL = 2.0
TRAJECTORY_TOL = 1e-12


def fmt(value):
    """Format a float with full round-trip precision (17 significant digits)."""
    return format(float(value), ".17g")


def base_header(extra=()):
    """Comment header lines: generator identity and library versions only."""
    lines = [
        f"# generated by {GENERATOR_NAME}",
        f"# numpy {np.__version__} scipy {scipy.__version__}",
    ]
    lines.extend(extra)
    return lines


# ---------------------------------------------------------------------------
# lagrange_points.csv
# ---------------------------------------------------------------------------

def generate_lagrange_lines():
    columns = ["system", "point", "x", "y", "jacobi"]
    rows = []
    for name, system in SYSTEMS.items():
        points = lagrange_points(system.mu)
        constants = lagrange_point_jacobi_constants(system.mu)
        for i, (pos, c_jacobi) in enumerate(zip(points, constants), start=1):
            rows.append([name, f"L{i}", fmt(pos[0]), fmt(pos[1]), fmt(c_jacobi)])
    header = base_header(
        ["# normalized rotating-frame coordinates; jacobi = C = 2*Omega at the point"]
    )
    return header + [",".join(columns)] + [",".join(r) for r in rows]


# ---------------------------------------------------------------------------
# Earth-Moon L1 planar Lyapunov orbit (shared by trajectories + floquet)
# ---------------------------------------------------------------------------

def _downward_y_crossing(t, y):
    """Event: y = 0 crossing while y is decreasing (vy < 0)."""
    return y[1]


_downward_y_crossing.terminal = True
_downward_y_crossing.direction = -1.0


def _first_perpendicular_residual(x0, vy0, mu):
    """vx and time at the first downward y=0 crossing from (x0, 0, 0, 0, vy0, 0)."""
    state = np.array([x0, 0.0, 0.0, 0.0, vy0, 0.0])
    # Start at t=1e-8: y(0)=0 would otherwise sit exactly on the event surface.
    result = propagate_with_events(
        state, (1e-8, 6.0), mu, [_downward_y_crossing], rtol=1e-12, atol=1e-12
    )
    return result.y[-1, 3], result.t[-1]


def find_l1_lyapunov_orbit(mu=MU_EARTH_MOON, ax=LYAPUNOV_AX):
    """
    Compute a planar Lyapunov orbit about Earth-Moon L1 using the oracle.

    The orbit starts at the left x-extreme (x0 = xL1 - ax, vy0 > 0) so the
    first downward y=0 crossing is the true half period.  vy0 is bracketed
    from the linearized in-plane mode (via the oracle's
    linearized_dynamics_at_lagrange) and refined with a 1-D root solve on
    vx(T/2); the well-conditioned seed is then polished by the oracle's
    differential_correction_planar.  The seeding is needed because
    periodic.find_lyapunov_orbit's built-in initial guess (vy = +0.2*Ax)
    collapses to the L1 equilibrium (see final report / known oracle issues).
    """
    x_l1 = lagrange_point_L1(mu)[0]
    x0 = x_l1 - ax

    # Linearized in-plane mode: frequency omega and velocity ratio kappa.
    matrix_a, _ = linearized_dynamics_at_lagrange(np.array([x_l1, 0.0, 0.0]), mu)
    u_yy = matrix_a[4, 1]
    omega_z = np.sqrt(-matrix_a[5, 2])
    eig_a = np.linalg.eigvals(matrix_a)
    in_plane = [
        abs(e.imag)
        for e in eig_a
        if abs(e.real) < 1e-9 and abs(e.imag) > 1e-9 and abs(abs(e.imag) - omega_z) > 1e-6
    ]
    omega = in_plane[0]
    kappa = 2.0 * omega / (omega**2 + u_yy)
    vy_linear = kappa * omega * ax  # displacement is -ax, so vy0 = +kappa*omega*ax

    # Bracket the true vy0 on the primary crossing branch (t_half < 2.0).
    samples = []
    for factor in np.linspace(0.8, 1.6, 17):
        vy = vy_linear * factor
        vx_half, t_half = _first_perpendicular_residual(x0, vy, mu)
        if t_half < 2.0:
            samples.append((vy, vx_half))
    bracket = None
    for (vy_a, fa), (vy_b, fb) in zip(samples, samples[1:]):
        if fa * fb < 0.0:
            bracket = (vy_a, vy_b)
            break
    if bracket is None:
        raise RuntimeError("no sign change found while bracketing Lyapunov vy0")

    from scipy.optimize import brentq

    vy_seed = brentq(
        lambda v: _first_perpendicular_residual(x0, v, mu)[0],
        bracket[0],
        bracket[1],
        xtol=1e-13,
        rtol=8.9e-16,
    )
    _, t_half_seed = _first_perpendicular_residual(x0, vy_seed, mu)

    seed = np.array([x0, 0.0, 0.0, 0.0, vy_seed, 0.0])
    state, period, converged = differential_correction_planar(
        seed, t_half_seed, mu, tol=1e-10, max_iter=60
    )
    if not converged:
        raise RuntimeError("differential_correction_planar failed to converge")

    # Independent closure check with the adaptive integrator.
    check = propagate(state, (0.0, period), mu, method="RK45", tol=1e-12, max_step=0.01)
    closure = float(np.max(np.abs(check.y[-1, :6] - state)))
    if closure > 1e-8:
        raise RuntimeError(f"Lyapunov orbit failed closure check: {closure:.3e}")

    return PeriodicOrbit(
        initial_state=state,
        period=float(period),
        jacobi=float(jacobi_constant(state, mu)),
        orbit_type="lyapunov",
        family="L1",
    )


# ---------------------------------------------------------------------------
# trajectories.csv
# ---------------------------------------------------------------------------

def trajectory_cases(lyapunov_orbit):
    """Well-conditioned, non-chaotic Earth-Moon test arcs (t = 2.0)."""
    mu = MU_EARTH_MOON
    return [
        # The corrected L1 Lyapunov orbit itself (bounded, periodic).
        ("l1_lyapunov", lyapunov_orbit.initial_state.copy()),
        # Distant retrograde orbit seed about the Moon (strongly stable
        # region); small z offset exercises the out-of-plane dynamics.
        ("dro_seed", np.array([1.0 - mu - 0.1, 0.0, 0.005, 0.0, 0.5, 0.0])),
        # Low prograde orbit about the Moon (near two-body regime).
        ("low_prograde_moon", np.array([1.0 - mu - 0.03, 0.0, 0.0, 0.0, -0.606, 0.0])),
        # Small zero-velocity libration displacement from L4 (stable for
        # Earth-Moon since mu < Routh critical ratio).
        ("l4_libration", np.array([0.5 - mu + 0.01, np.sqrt(3.0) / 2.0, 0.0, 0.0, 0.0, 0.0])),
    ]


def generate_trajectory_lines(lyapunov_orbit):
    mu = MU_EARTH_MOON
    columns = [
        "case", "mu", "x0", "y0", "z0", "vx0", "vy0", "vz0", "t_final",
        "xf", "yf", "zf", "vxf", "vyf", "vzf", "jacobi_drift",
    ]
    rows = []
    for name, state0 in trajectory_cases(lyapunov_orbit):
        result = propagate(
            state0, (0.0, TRAJECTORY_T_FINAL), mu, method="RK45", tol=TRAJECTORY_TOL
        )
        if not result.success:
            raise RuntimeError(f"propagation failed for case {name}: {result.message}")
        final = result.y[-1, :6]
        drift = float(np.max(np.abs(result.jacobi - result.jacobi[0])))
        rows.append(
            [name, fmt(mu)]
            + [fmt(v) for v in state0]
            + [fmt(TRAJECTORY_T_FINAL)]
            + [fmt(v) for v in final]
            + [fmt(drift)]
        )
    header = base_header(
        [
            "# oracle adaptive RK45 (scipy solve_ivp), rtol=atol=1e-12, Earth-Moon frame",
            "# jacobi_drift = max |C(t) - C(0)| along the arc",
        ]
    )
    return header + [",".join(columns)] + [",".join(r) for r in rows]


# ---------------------------------------------------------------------------
# floquet.csv
# ---------------------------------------------------------------------------

def sorted_monodromy_eigenvalues(monodromy):
    """Eigenvalues sorted by |lambda| desc, ties by Re desc then Im desc."""
    eigenvalues = np.linalg.eigvals(monodromy)
    order = np.lexsort((-eigenvalues.imag, -eigenvalues.real, -np.abs(eigenvalues)))
    return eigenvalues[order]


def generate_floquet_lines(lyapunov_orbit):
    mu = MU_EARTH_MOON
    monodromy = compute_monodromy_matrix(lyapunov_orbit, mu, dt=1e-4)
    eigenvalues = sorted_monodromy_eigenvalues(monodromy)

    columns = ["mu", "x0", "vy0", "period"]
    values = [
        fmt(mu),
        fmt(lyapunov_orbit.initial_state[0]),
        fmt(lyapunov_orbit.initial_state[4]),
        fmt(lyapunov_orbit.period),
    ]
    for i, ev in enumerate(eigenvalues, start=1):
        columns.extend([f"ev{i}_re", f"ev{i}_im"])
        values.extend([fmt(ev.real), fmt(ev.imag)])

    header = base_header(
        [
            "# planar Lyapunov orbit about Earth-Moon L1; state = [x0,0,0,0,vy0,0]",
            "# monodromy from fixed-step RK4 STM propagation, dt=1e-4, one period",
            "# eigenvalues sorted by |lambda| descending; the trivial unit pair is a",
            "# defective Jordan block: compare ev columns with abs tolerance 1e-5",
        ]
    )
    return header + [",".join(columns)] + [",".join(values)]


# ---------------------------------------------------------------------------
# Generation / check driver
# ---------------------------------------------------------------------------

def generate_all():
    """Regenerate every reference file in memory: {filename: [lines]}."""
    lyapunov_orbit = find_l1_lyapunov_orbit()
    return {
        "lagrange_points.csv": generate_lagrange_lines(),
        "trajectories.csv": generate_trajectory_lines(lyapunov_orbit),
        "floquet.csv": generate_floquet_lines(lyapunov_orbit),
    }


def write_all(files):
    DATA_DIR.mkdir(parents=True, exist_ok=True)
    for name, lines in files.items():
        path = DATA_DIR / name
        path.write_text("\n".join(lines) + "\n")
        print(f"wrote {path.relative_to(REPO_ROOT)} ({len(lines)} lines)")


def _tolerances_for(filename, column):
    if filename == "floquet.csv" and column.startswith("ev"):
        return EV_REL_TOL, EV_ABS_FLOOR
    if filename == "trajectories.csv":
        if column == "jacobi_drift":
            return TRAJ_REL_TOL, DRIFT_ABS_FLOOR
        return TRAJ_REL_TOL, TRAJ_ABS_FLOOR
    return REL_TOL, ABS_FLOOR


def _compare_file(filename, expected_lines, actual_lines, report):
    """Compare regenerated lines against committed lines. Appends diffs to report."""
    ok = True
    exp_comments = [line for line in expected_lines if line.startswith("# ")]
    act_comments = [line for line in actual_lines if line.startswith("# ")]
    if exp_comments != act_comments:
        report.append(f"{filename}: comment header mismatch")
        report.append(f"  committed : {act_comments}")
        report.append(f"  regenerated: {exp_comments}")
        ok = False

    exp_data = [line for line in expected_lines if not line.startswith("# ")]
    act_data = [line for line in actual_lines if not line.startswith("# ")]
    if not act_data or not exp_data:
        report.append(f"{filename}: missing data section")
        return False
    if exp_data[0] != act_data[0]:
        report.append(f"{filename}: column header mismatch")
        report.append(f"  committed : {act_data[0]}")
        report.append(f"  regenerated: {exp_data[0]}")
        return False
    columns = exp_data[0].split(",")
    if len(exp_data) != len(act_data):
        report.append(
            f"{filename}: row count mismatch (committed {len(act_data) - 1}, "
            f"regenerated {len(exp_data) - 1})"
        )
        return False

    for row_idx, (exp_row, act_row) in enumerate(zip(exp_data[1:], act_data[1:]), start=1):
        exp_fields = exp_row.split(",")
        act_fields = act_row.split(",")
        if len(exp_fields) != len(act_fields):
            report.append(f"{filename} row {row_idx}: field count mismatch")
            ok = False
            continue
        for col, exp_f, act_f in zip(columns, exp_fields, act_fields):
            try:
                exp_v = float(exp_f)
                act_v = float(act_f)
            except ValueError:
                if exp_f != act_f:
                    report.append(
                        f"{filename} row {row_idx} col {col}: "
                        f"'{act_f}' (committed) != '{exp_f}' (regenerated)"
                    )
                    ok = False
                continue
            rel_tol, abs_floor = _tolerances_for(filename, col)
            diff = abs(exp_v - act_v)
            limit = max(rel_tol * abs(exp_v), abs_floor)
            if diff > limit:
                report.append(
                    f"{filename} row {row_idx} col {col}: committed={act_f} "
                    f"regenerated={exp_f} |diff|={diff:.3e} > tol={limit:.3e}"
                )
                ok = False
    return ok


def check_all(files):
    report = []
    all_ok = True
    for name, expected_lines in files.items():
        path = DATA_DIR / name
        if not path.is_file():
            report.append(f"{name}: missing committed file {path}")
            all_ok = False
            continue
        actual_lines = path.read_text().splitlines()
        if not _compare_file(name, expected_lines, actual_lines, report):
            all_ok = False

    if all_ok:
        print(f"check OK: {len(files)} reference files match regenerated values")
        print(f"  tolerances: rel {REL_TOL:g} / abs floor {ABS_FLOOR:g}"
              f" (eigenvalue columns: rel {EV_REL_TOL:g} / abs floor {EV_ABS_FLOOR:g})")
        return 0
    print("check FAILED:")
    for line in report:
        print("  " + line)
    return 1


def main(argv=None):
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[1])
    parser.add_argument(
        "--check",
        action="store_true",
        help="regenerate in memory and compare against committed CSVs (CI drift gate)",
    )
    args = parser.parse_args(argv)

    files = generate_all()
    if args.check:
        return check_all(files)
    write_all(files)
    return 0


if __name__ == "__main__":
    sys.exit(main())
