import type { Production, ProductionFamily, Storyboard } from "./types";

function board(
  colorName: string,
  colorHex: string,
  accentHex: string,
  astronaut: string,
  logline: string,
  beats: Storyboard["beats"],
): Storyboard {
  return { colorName, colorHex, accentHex, astronaut, logline, beats };
}

type Seed = Omit<Production, "id">;

const SEEDS: Seed[] = [
  {
    slug: "leo-geo-hohmann",
    title: "The Climb",
    family: "maneuver",
    haleRef: "Hale Ch. 6 — Hohmann",
    adaRef: "hale_orbital-maneuvers.adb / hohmann_transfer.adb",
    synopsis: "LEO 300 km to GEO. Two burns. Five hours of waiting.",
    runnable: true,
    shots: 12,
    targetMinutes: 3,
    storyboard: board(
      "copper dawn",
      "#c48a4a",
      "#f0d3a8",
      "A transfer-stage pilot watches Earth flatten from a porthole while the second burn clock ticks in GEO twilight.",
      "Two impulses. One coast. A human sitting still while the vis-viva equation does the work.",
      [
        { t: "0:00", shot: "Gloves on a cold window. LEO sunrise stripes the cabin copper.", camera: "tight interior, 35mm", fromFinding: "v_circ LEO" },
        { t: "0:18", shot: "First burn — the stack leans, Earth slides.", camera: "side-on exterior, 85mm", fromFinding: "Δv1" },
        { t: "1:10", shot: "Transfer ellipse. The planet shrinks. Nobody talks.", camera: "wide receding", fromFinding: "a_transfer, TOF" },
        { t: "2:40", shot: "GEO circularize. The disk becomes a marble. Second burn.", camera: "over-shoulder at the clock", fromFinding: "Δv2" },
      ],
    ),
  },
  {
    slug: "iss-phasing",
    title: "Catching the Station",
    family: "maneuver",
    haleRef: "Hale Ch. 6 — phasing",
    adaRef: "hale_orbital-maneuvers.adb",
    synopsis: "Phasing orbit to chase the ISS through one night pass.",
    runnable: false,
    shots: 10,
    targetMinutes: 3,
    storyboard: board("sodium night", "#d4a017", "#fff1c2", "A Soyuz commander times a 90-minute chase against city-light veins.", "Catch a house moving at 7.66 km/s.", []),
  },
  {
    slug: "plane-change-51",
    title: "The Tilt",
    family: "maneuver",
    haleRef: "Hale §6.6 plane change",
    adaRef: "hale_orbital-maneuvers.adb",
    synopsis: "28.5° to 51.6° combined plane change. Expensive and honest.",
    runnable: false,
    shots: 8,
    targetMinutes: 2,
    storyboard: board("cold steel", "#8aa0b0", "#d7e4ee", "EVA tether slack as the stack yaws through the node.", "Inclination is the tax you pay in propellant.", []),
  },
  {
    slug: "bielliptic-outer",
    title: "The Long Way",
    family: "maneuver",
    haleRef: "Hale §6.3 bi-elliptic",
    adaRef: "Bielliptic_Transfer",
    synopsis: "When r2/r1 > 11.94 the long way is cheaper.",
    runnable: false,
    shots: 11,
    targetMinutes: 4,
    storyboard: board("deep rust", "#8c3b2a", "#e8b59a", "A cargo crew spends weeks at apoapsis, Earth a star.", "The cheap burn is the one you wait for.", []),
  },
  {
    slug: "escape-c3",
    title: "Leaving",
    family: "two-body",
    haleRef: "Hale Ch. 3 escape",
    adaRef: "hale_orbital-twobody.adb",
    synopsis: "C3 = 0. The last bound ellipse opens.",
    runnable: false,
    shots: 9,
    targetMinutes: 3,
    storyboard: board("bone white", "#e8e2d4", "#9a9386", "An astronaut unclips a farewell patch as the escape burn lights.", "Parabolic is a feeling.", []),
  },
  {
    slug: "molniya",
    title: "The High North",
    family: "two-body",
    haleRef: "Hale Ch. 3 Molniya",
    adaRef: "hale_orbital-elements.adb",
    synopsis: "12-hour critical-inclination dwell over Siberia.",
    runnable: false,
    shots: 8,
    targetMinutes: 3,
    storyboard: board("aurora green", "#3d6b4f", "#c8e6c0", "A comms officer watches aurora crawl under a 12-hour apogee hang.", "Time is spent where the ground needs you.", []),
  },
  {
    slug: "tundra",
    title: "One Day Over the City",
    family: "two-body",
    haleRef: "Hale Ch. 3 Tundra",
    adaRef: "hale_orbital-elements.adb",
    synopsis: "24-hour eccentric, hanging over one meridian.",
    runnable: false,
    shots: 8,
    targetMinutes: 3,
    storyboard: board("civic gold", "#c9a227", "#fff4c4", "A weather-sat operator eats lunch under a parked apogee.", "A day, exactly.", []),
  },
  {
    slug: "geo-eclipse",
    title: "The Shadow",
    family: "observatory",
    haleRef: "Hale Ch. 2 eclipse geometry",
    adaRef: "hale_orbital-twobody.adb",
    synopsis: "GEO spacecraft rides Earth's umbra at equinox.",
    runnable: false,
    shots: 10,
    targetMinutes: 3,
    storyboard: board("umbra violet-black", "#1c1424", "#c9b8a0", "A GEO sat operator sits in a dark control room as arrays go cold.", "72 minutes of battery and nerve.", []),
  },
  {
    slug: "j2-precess",
    title: "The Wobble",
    family: "two-body",
    haleRef: "Hale Ch. 5 perturbations",
    adaRef: "hale_orbital-elements.adb",
    synopsis: "J2 nodal precession as a SSO designer.",
    runnable: false,
    shots: 8,
    targetMinutes: 2,
    storyboard: board("slate", "#6d7278", "#d5d8db", "A mapper times local solar hour against Earth's bulge.", "The planet is not a point mass.", []),
  },
  {
    slug: "sso-dawn",
    title: "Always Morning",
    family: "two-body",
    haleRef: "Hale Ch. 5 SSO",
    adaRef: "hale_orbital-elements.adb",
    synopsis: "Sun-synchronous 98° — dawn forever.",
    runnable: false,
    shots: 9,
    targetMinutes: 3,
    storyboard: board("terminator amber", "#d9893b", "#ffe0b8", "A recon photographer lives on the terminator, never seeing night.", "The Sun is a clock, not a star.", []),
  },
  {
    slug: "gps-constellation",
    title: "Twenty-Four Clocks",
    family: "two-body",
    haleRef: "Hale Ch. 3 MEO",
    adaRef: "hale_orbital-twobody.adb",
    synopsis: "MEO 20 180 km. Period as a timepiece.",
    runnable: false,
    shots: 8,
    targetMinutes: 2,
    storyboard: board("instrument cyan", "#5aa3b5", "#d4f0f5", "A navigator walks a city with four ghosts overhead.", "Position is four ranges.", []),
  },
  {
    slug: "jwst-halo",
    title: "The Cold Eye",
    family: "cr3bp",
    haleRef: "Hale Ch. 10 L2 / halo",
    adaRef: "hale_orbital-threebody.adb Find_Halo_Orbit",
    synopsis: "Sun-Earth L2. JWST's northern halo. The shade never sees the Sun.",
    runnable: true,
    shots: 14,
    targetMinutes: 4,
    storyboard: board(
      "infrared gold",
      "#c9a36b",
      "#f4e4c4",
      "A mission astronomer in Baltimore watches first light while the telescope hangs 1.5 million km behind the Earth, never turning toward the Sun.",
      "A saddle in a rotating frame. A gold shield. A person waiting for photons that left a galaxy when we were fish.",
      [
        { t: "0:00", shot: "Sun-Earth rotating frame. Two masses. Five quiet points.", camera: "schematic → physical", fromFinding: "μ Sun-Earth" },
        { t: "0:40", shot: "Newton on the L2 quintic. The point locks.", camera: "numbers into a star field", fromFinding: "L2 x, km" },
        { t: "1:20", shot: "A gold pentagon at L2. Earth a pale coin. The Sun forever behind the shade.", camera: "JWST three-quarter", fromFinding: "distance Earth→L2" },
        { t: "2:30", shot: "A small kick off the equilibrium. The saddle unfolds. Jacobi holds.", camera: "trail in the rotating frame", fromFinding: "Jacobi residual" },
        { t: "3:20", shot: "An astronomer touches the screen. First spectrum.", camera: "hands, then the mirror", fromFinding: "C at L2" },
      ],
    ),
  },
  {
    slug: "soho-l1",
    title: "Never Night",
    family: "cr3bp",
    haleRef: "Hale Ch. 10 L1",
    adaRef: "Compute_Lagrange_Point L1",
    synopsis: "Sun-Earth L1. SOHO stares at the Sun without eclipse.",
    runnable: true,
    shots: 12,
    targetMinutes: 3,
    storyboard: board(
      "solar white",
      "#f2ead8",
      "#e07a3d",
      "A solar physicist drinks cold coffee at 3 a.m. while a spacecraft 1.5 million km sunward never enters Earth's shadow.",
      "The point between two fires.",
      [
        { t: "0:00", shot: "Photosphere fills the frame. A disk, not a star.", camera: "SOHO coronagraph feel", fromFinding: "L1 x" },
        { t: "0:50", shot: "L1 locks between Sun and Earth.", camera: "rotating-frame schematic", fromFinding: "Earth→L1 km" },
        { t: "1:40", shot: "A CME lifts. The physicist stands up.", camera: "control-room glass", fromFinding: "Jacobi C_L1" },
        { t: "2:30", shot: "Perturb L1. The saddle throws the craft sunward or home.", camera: "RK4 trail", fromFinding: "saddle residual" },
      ],
    ),
  },
  {
    slug: "earth-moon-l4",
    title: "The Trojan Dust",
    family: "cr3bp",
    haleRef: "Hale Ch. 10 L4",
    adaRef: "Compute_Lagrange_Point L4 / Analyze_Stability",
    synopsis: "Earth-Moon L4. Routh-stable. A cloud of dust and a visiting crew.",
    runnable: true,
    shots: 12,
    targetMinutes: 3,
    storyboard: board(
      "bone moonlight",
      "#cfc6b8",
      "#7a8b9a",
      "A geologist on a visiting lander scoops Kordylewski dust while Earth and Moon hold an equilateral triangle around her.",
      "Sixty degrees ahead. Stable if μ is small enough.",
      [
        { t: "0:00", shot: "Earth, Moon, and a third light — L4, not a body.", camera: "wide rotating frame", fromFinding: "L4 analytic" },
        { t: "0:40", shot: "Routh: μ < 0.03852. Earth-Moon passes.", camera: "handwritten inequality", fromFinding: "μ vs μ_c" },
        { t: "1:20", shot: "A lander hangs in moonlight-colored dust.", camera: "helmet lamp", fromFinding: "L4 km" },
        { t: "2:20", shot: "A tadpole orbit. The geologist does not fall toward either world.", camera: "RK4 around L4", fromFinding: "Jacobi conserved" },
      ],
    ),
  },
  {
    slug: "earth-moon-l5",
    title: "Trailing",
    family: "cr3bp",
    haleRef: "Hale Ch. 10 L5",
    adaRef: "Compute_Lagrange_Point L5",
    synopsis: "The other triangle. A depot waiting.",
    runnable: false,
    shots: 10,
    targetMinutes: 3,
    storyboard: board("ash silver", "#b8b4ae", "#5c6570", "A depot keeper lives 60° behind the Moon and counts visiting tugs.", "Same math. Different sky.", []),
  },
  {
    slug: "gateway-l1",
    title: "The Gate",
    family: "cr3bp",
    haleRef: "Hale Ch. 10 Earth-Moon L1",
    adaRef: "Find_Lyapunov_Orbit L1",
    synopsis: "Earth-Moon L1 Lyapunov. A gateway station on a figure-eight.",
    runnable: false,
    shots: 13,
    targetMinutes: 4,
    storyboard: board("airlock red", "#9a3b32", "#f0cfc8", "A construction EVA at Earth-Moon L1. Earth in one window, Moon in the other.", "The saddle you build a house on.", []),
  },
  {
    slug: "far-side-l2",
    title: "The Quiet Face",
    family: "cr3bp",
    haleRef: "Hale Ch. 10 Earth-Moon L2",
    adaRef: "Find_Halo_Orbit L2",
    synopsis: "Relay halo over the lunar far side.",
    runnable: false,
    shots: 11,
    targetMinutes: 3,
    storyboard: board("far-side indigo", "#2a3348", "#c9b89a", "A radio astronomer lands where Earth has never risen.", "The Moon is a shield.", []),
  },
  {
    slug: "zvc-earth-moon",
    title: "The Forbidden Sea",
    family: "cr3bp",
    haleRef: "Hale Ch. 10 zero-velocity",
    adaRef: "Pseudo_Potential / Jacobi_Constant",
    synopsis: "Zero-velocity curves open L1 like a neck.",
    runnable: false,
    shots: 10,
    targetMinutes: 3,
    storyboard: board("ink wash", "#1a1c1e", "#d8c3a5", "A navigator traces a forbidden region with a gloved finger.", "Energy is a wall.", []),
  },
  {
    slug: "lyapunov-family",
    title: "The Family",
    family: "cr3bp",
    haleRef: "Hale Ch. 10 Lyapunov",
    adaRef: "Generate_Orbit_Family",
    synopsis: "Continuation of planar periodic orbits around L1.",
    runnable: false,
    shots: 10,
    targetMinutes: 3,
    storyboard: board("graphite", "#6e6a62", "#e6e0d4", "An analyst overlays a family until the last orbit kisses the Moon.", "One amplitude at a time.", []),
  },
  {
    slug: "halo-richardson",
    title: "Third Order",
    family: "cr3bp",
    haleRef: "Richardson 1980 / Hale Ch. 10",
    adaRef: "Richardson_Halo_Guess",
    synopsis: "Third-order halo seed before differential correction.",
    runnable: false,
    shots: 9,
    targetMinutes: 3,
    storyboard: board("brass equation", "#b0894a", "#f3e2c4", "A student writes Richardson's series on a window overlooking a clean room.", "The guess is already almost a halo.", []),
  },
  {
    slug: "earth-mars",
    title: "The Window",
    family: "interplanetary",
    haleRef: "Hale Ch. 8 patched conic",
    adaRef: "earth_mars_mission.adb",
    synopsis: "26-month synodic. Hohmann to Mars.",
    runnable: false,
    shots: 16,
    targetMinutes: 5,
    storyboard: board("rust planet", "#b85c38", "#f0d2b8", "A transit crew watches Earth become a star. Someone plays a song too early.", "Eight months is a marriage.", []),
  },
];

const MORE: Array<{
  title: string;
  family: ProductionFamily;
  haleRef: string;
  adaRef: string;
  synopsis: string;
  colorName: string;
  colorHex: string;
  accentHex: string;
  astronaut: string;
  logline: string;
}> = [
  { title: "Porkchop Winter", family: "lambert", haleRef: "Hale Ch. 7 Lambert", adaRef: "lambert_intercept.adb", synopsis: "A porkchop plot as a weather map.", colorName: "chartreuse heat", colorHex: "#c4c76a", accentHex: "#2a2c1e", astronaut: "A trajectory designer circles one contour with a grease pencil.", logline: "Every color is a Δv." },
  { title: "The Intercept", family: "lambert", haleRef: "Hale Ch. 7", adaRef: "Hale_Orbital.Lambert", synopsis: "Two-impulse intercept of a tumbling stage.", colorName: "warning amber", colorHex: "#e09a2b", accentHex: "#2b2112", astronaut: "A rescue pilot flies the Lambert solution by the book.", logline: "Time of flight is the argument." },
  { title: "Venus Nightside", family: "interplanetary", haleRef: "Hale Ch. 8", adaRef: "hale_orbital-interplanetary.adb", synopsis: "Type-II to Venus. Radar through cloud.", colorName: "sulfur", colorHex: "#c9b44a", accentHex: "#3a3414", astronaut: "A radar scientist waits out a 4-month blackout.", logline: "The planet hides." },
  { title: "Mercury Messenger", family: "interplanetary", haleRef: "Hale Ch. 8 gravity assist", adaRef: "hale_orbital-interplanetary.adb", synopsis: "Resonant Venus assists to kill energy.", colorName: "scorched iron", colorHex: "#8a4a32", accentHex: "#e8c4b0", astronaut: "A navigator counts flybys like beads.", logline: "You cannot Hohmann to Mercury and live." },
  { title: "Jupiter Burn", family: "interplanetary", haleRef: "Hale Ch. 8", adaRef: "hale_orbital-interplanetary.adb", synopsis: "HOHMANN numbers so large they look fake.", colorName: "band ochre", colorHex: "#c49a4a", accentHex: "#24180c", astronaut: "A probe team watches a 2-year coast end in a 40-minute capture.", logline: "The giant does not forgive." },
  { title: "Europa Clip", family: "cr3bp", haleRef: "Hale Ch. 10 Jovian", adaRef: "Sun_Jupiter_System", synopsis: "Sun-Jupiter L-points as a map to the moons.", colorName: "ice crack", colorHex: "#9bb8c9", accentHex: "#1c2830", astronaut: "An ice-pen author sketches a flyby over a cracked moon.", logline: "The ocean is under the math." },
  { title: "Trojan Camp", family: "cr3bp", haleRef: "Hale Ch. 10 L4 Sun-Jupiter", adaRef: "Compute_Lagrange_Point L4", synopsis: "A camp at the Greek camp of Jupiter.", colorName: "campfire", colorHex: "#d9893b", accentHex: "#2a1808", astronaut: "A surveyor plants a stake in a cloud of ancient rock.", logline: "Routh said we could stay." },
  { title: "Patched Sphere", family: "interplanetary", haleRef: "Hale Ch. 8 SOI", adaRef: "hale_orbital-interplanetary.adb", synopsis: "Sphere of influence as a door.", colorName: "threshold grey", colorHex: "#8a8680", accentHex: "#e8e4dc", astronaut: "A navigator calls 'SOI inbound' like a sailor calling land.", logline: "Two-body, then another two-body." },
  { title: "C3 Map", family: "interplanetary", haleRef: "Hale Ch. 8 departure", adaRef: "hale_orbital-twobody.adb", synopsis: "Earth departure energy as a weather chart.", colorName: "launch white", colorHex: "#e8e6e1", accentHex: "#4a4844", astronaut: "A launch director reads C3 off a board and nods once.", logline: "Energy is a ticket." },
  { title: "Aerocapture", family: "interplanetary", haleRef: "Hale atmosphere notes", adaRef: "hale_orbital-twobody.adb", synopsis: "A skip through Mars air instead of a burn.", colorName: "plasma peach", colorHex: "#e07a4a", accentHex: "#2a1208", astronaut: "A pilot rides a plasma window and does not blink.", logline: "The atmosphere is a thruster." },
  { title: "Ballistic Capture", family: "cr3bp", haleRef: "Hale Ch. 10 WSB", adaRef: "Propagate CR3BP", synopsis: "Weak stability boundary. Arrive without a big burn.", colorName: "quiet teal", colorHex: "#3d6b6a", accentHex: "#d4ece8", astronaut: "A cargo skipper whispers the ship into lunar orbit.", logline: "The three-body problem is a gift." },
  { title: "Heteroclinic", family: "cr3bp", haleRef: "Koon / Hale Ch. 10", adaRef: "Propagate_With_STM", synopsis: "L1 to L2 on a tube. No propellant.", colorName: "tube violet-grey", colorHex: "#6a6578", accentHex: "#e4dce8", astronaut: "A theoretician watches a tube and does not smile, then does.", logline: "Unstable manifolds are roads." },
  { title: "Monodromy", family: "cr3bp", haleRef: "Hale Ch. 10 Floquet", adaRef: "Analyze_Floquet", synopsis: "Six multipliers. One of them wants to leave.", colorName: "eigen red", colorHex: "#a33b32", accentHex: "#f0d4d0", astronaut: "A dynamicist circles |λ| > 1 in red pencil.", logline: "Stability is a number." },
  { title: "STM Breath", family: "cr3bp", haleRef: "Hale Ch. 10 STM", adaRef: "Propagate_With_STM", synopsis: "A 6×6 matrix breathing along a halo.", colorName: "matrix green-grey", colorHex: "#4a5c52", accentHex: "#d4e4d8", astronaut: "A GNC engineer watches Φ tick and corrects once.", logline: "The future of a kick." },
  { title: "Northern Halo", family: "cr3bp", haleRef: "Hale Ch. 10", adaRef: "Halo_Northern", synopsis: "Az > 0. The family that JWST joined.", colorName: "north gold", colorHex: "#c9a36b", accentHex: "#2a2418", astronaut: "A telescope operator names the family out loud.", logline: "North is a choice of sign." },
  { title: "Southern Halo", family: "cr3bp", haleRef: "Hale Ch. 10", adaRef: "Halo_Southern", synopsis: "The other sign. Same math, other sky.", colorName: "south copper", colorHex: "#b8734a", accentHex: "#2a1810", astronaut: "A twin crew takes the southern house.", logline: "Symmetry is a second home." },
  { title: "L3 Ghost", family: "cr3bp", haleRef: "Hale Ch. 10 L3", adaRef: "Compute_Lagrange_Point L3", synopsis: "The point on the far side of the Sun.", colorName: "occulted", colorHex: "#3a3834", accentHex: "#d8d0c4", astronaut: "A sentinel sits where Earth can never see.", logline: "Opposite. Always." },
  { title: "Sun-Mars L1", family: "cr3bp", haleRef: "Hale Ch. 10", adaRef: "threebody systems", synopsis: "A weather buoy between Sun and Mars.", colorName: "dust rose", colorHex: "#c47a6a", accentHex: "#2a1614", astronaut: "A climatologist parks a buoy in a saddle.", logline: "Forecast from a point that is not a place." },
  { title: "Sun-Venus L2", family: "cr3bp", haleRef: "Hale Ch. 10", adaRef: "threebody systems", synopsis: "Nightside watcher of a greenhouse.", colorName: "cloud sulfur", colorHex: "#c9b86a", accentHex: "#2a2610", astronaut: "An atmospheric chemist never sees the dayside.", logline: "The shade is the instrument." },
  { title: "Tadpole", family: "cr3bp", haleRef: "Hale Ch. 10 L4 motion", adaRef: "Propagate RK4", synopsis: "A tadpole orbit around L4, drawn slowly.", colorName: "pond silver", colorHex: "#a8b4b0", accentHex: "#1c2422", astronaut: "A pilot rides a tadpole and laughs once.", logline: "Stable is not still." },
  { title: "Horseshoe", family: "cr3bp", haleRef: "Hale Ch. 10", adaRef: "Propagate", synopsis: "A horseshoe that almost visits both triangles.", colorName: "iron oxide", colorHex: "#8a5a3a", accentHex: "#f0d8c4", astronaut: "A courier runs the long shoe for a year.", logline: "You can orbit a point that is empty." },
  { title: "Hill Sphere", family: "cr3bp", haleRef: "Hale Ch. 10 Hill", adaRef: "R1 / R2 helpers", synopsis: "Where the Moon keeps her own.", colorName: "boundary chalk", colorHex: "#d8d2c4", accentHex: "#3a3830", astronaut: "A student draws Hill's surface on a blackboard and then erases it.", logline: "Ownership is a radius." },
  { title: "CR3BP Promise", family: "cr3bp", haleRef: "Hale Ch. 10", adaRef: "hale_orbital-threebody.ads", synopsis: "The rotating frame explained to a new crew.", colorName: "primer grey", colorHex: "#8a8884", accentHex: "#e8e4dc", astronaut: "An instructor spins a model of two masses until someone gets it.", logline: "The frame is the trick." },
  { title: "Kepler Wait", family: "two-body", haleRef: "Hale Ch. 4", adaRef: "hale_orbital-kepler.adb", synopsis: "Newton on Kepler's equation, on camera.", colorName: "notebook tan", colorHex: "#c4b49a", accentHex: "#2a2418", astronaut: "A student solves E − e sin E = M by hand, then the machine agrees.", logline: "Anomaly is not an accident." },
  { title: "Universal Z", family: "two-body", haleRef: "Hale Ch. 4 universal", adaRef: "hale_orbital-stumpff.adb", synopsis: "Stumpff functions. One solver for all conics.", colorName: "function blue-grey", colorHex: "#6a7a88", accentHex: "#dce4ea", astronaut: "A GNC lead refuses three solvers. She wants one.", logline: "c(z) and s(z)." },
  { title: "Hyperbolic Flyby", family: "two-body", haleRef: "Hale Ch. 3 hyperbola", adaRef: "hale_orbital-twobody.adb", synopsis: "e > 1. A planet used as a hinge.", colorName: "slash white", colorHex: "#e8e6e1", accentHex: "#4a4038", astronaut: "A probe team times periapsis to the second.", logline: "You only get one pass." },
  { title: "Vis-Viva Recited", family: "two-body", haleRef: "Hale Eq. 2.19", adaRef: "Vis_Viva", synopsis: "A crew recites the equation before a burn.", colorName: "recitation cream", colorHex: "#e8dcc4", accentHex: "#3a3224", astronaut: "Someone says 'two over r minus one over a' like a prayer.", logline: "The only equation that matters today." },
  { title: "Angular Quiet", family: "two-body", haleRef: "Hale Ch. 2 h", adaRef: "Angular_Momentum", synopsis: "h conserved. A spin that never lies.", colorName: "axis white", colorHex: "#d8dce0", accentHex: "#2a3034", astronaut: "A pilot feels the plane of the orbit in her inner ear.", logline: "h is a direction." },
  { title: "Energy Ledger", family: "two-body", haleRef: "Hale Ch. 2 ε", adaRef: "Specific_Energy", synopsis: "ε as a bank balance.", colorName: "ledger green", colorHex: "#4a6b52", accentHex: "#d8ead8", astronaut: "A flight engineer balances ε before sleep.", logline: "Negative is home." },
  { title: "Period Song", family: "two-body", haleRef: "Hale Eq. 2.24", adaRef: "Orbital_Period", synopsis: "T = 2π√(a³/μ) set to a metronome.", colorName: "tempo rust", colorHex: "#a85a3a", accentHex: "#f0d4c4", astronaut: "A composer writes a piece in 92-minute time.", logline: "Orbits keep time." },
  { title: "True Anomaly", family: "two-body", haleRef: "Hale Ch. 3 ν", adaRef: "Radius_At_True_Anomaly", synopsis: "ν from 0 to 2π painted as a clock.", colorName: "clock gold", colorHex: "#c9a44a", accentHex: "#2a220c", astronaut: "A navigator points at periapsis like a priest at an altar.", logline: "Where you are on the oval." },
  { title: "Eccentric Walk", family: "two-body", haleRef: "Hale Ch. 4 E", adaRef: "solveKeplerElliptic", synopsis: "Auxiliary circle made visible.", colorName: "circle chalk", colorHex: "#d0c8b8", accentHex: "#3a3428", astronaut: "A teacher walks the auxiliary circle on a gym floor.", logline: "E is a helper, not a place." },
  { title: "Mean Lie", family: "two-body", haleRef: "Hale Ch. 4 M", adaRef: "Mean_From_E", synopsis: "M pretends the motion is uniform.", colorName: "lie grey", colorHex: "#8a8884", accentHex: "#e8e4dc", astronaut: "A cadet learns that mean is a fiction that works.", logline: "Uniform is the clock. Real is the ship." },
  { title: "Plane of Two", family: "two-body", haleRef: "Hale Ch. 2", adaRef: "hale_orbital-vectors.adb", synopsis: "r × v. The only plane that matters.", colorName: "plane ice", colorHex: "#b8c4cc", accentHex: "#1c2428", astronaut: "An EVA tracks the plane with a glove against the window.", logline: "You live in a sheet." },
  { title: "Node Crossing", family: "maneuver", haleRef: "Hale §6.6", adaRef: "Simple_Plane_Change", synopsis: "Burn only at the node or waste it.", colorName: "node red", colorHex: "#a33b32", accentHex: "#f0d4d0", astronaut: "A commander waits three hours for a line on a globe.", logline: "Geometry first. Then fire." },
  { title: "Rendezvous Clock", family: "maneuver", haleRef: "Hale Ch. 6", adaRef: "hale_orbital-maneuvers.adb", synopsis: "Two ships, one clock, one burn.", colorName: "docking amber", colorHex: "#d4a017", accentHex: "#2a2208", astronaut: "A docking pilot counts meters in the last 90 seconds.", logline: "Closing rate is a feeling." },
  { title: "Hohmann Down", family: "maneuver", haleRef: "Hale Ch. 6", adaRef: "Hohmann_Transfer", synopsis: "GEO to LEO. The climb in reverse.", colorName: "reentry copper", colorHex: "#b86a3a", accentHex: "#f0d4c0", astronaut: "A returning crew watches Earth swell.", logline: "Down is also two burns." },
  { title: "Escape from LEO", family: "maneuver", haleRef: "Hale Ch. 3", adaRef: "Escape_Delta_V", synopsis: "√2 − 1 times circular. The ticket out.", colorName: "ticket white", colorHex: "#e8e4dc", accentHex: "#4a443c", astronaut: "A departing crew toasts with pouches at C3 = 0.", logline: "One more forty percent." },
  { title: "GEO Slot", family: "observatory", haleRef: "Hale Ch. 3 GEO", adaRef: "R_GEO constant", synopsis: "A parking space over a meridian.", colorName: "slot navy", colorHex: "#2a3a4a", accentHex: "#d4c4a0", astronaut: "A fleet manager assigns a slot like a harbormaster.", logline: "Longitude is property." },
  { title: "ISS Night Pass", family: "observatory", haleRef: "Hale Ch. 3 LEO", adaRef: "ISS_ALTITUDE", synopsis: "A 92-minute day. Sixteen sunrises.", colorName: "cupola orange", colorHex: "#e07a3d", accentHex: "#2a1408", astronaut: "Someone in the cupola forgets to take the photo, then does.", logline: "Sixteen days in one day." },
  { title: "Polar Noon", family: "observatory", haleRef: "Hale Ch. 5", adaRef: "hale_orbital-elements.adb", synopsis: "i = 90°. Every latitude, none of the rest.", colorName: "ice white", colorHex: "#e8eef2", accentHex: "#2a3438", astronaut: "A mapper flies pole to pole and never sees the equator linger.", logline: "The whole Earth, in strips." },
  { title: "Eclipse from GEO", family: "observatory", haleRef: "Hale geometry", adaRef: "hale_orbital-twobody.adb", synopsis: "The Earth becomes a black coin on the Sun.", colorName: "diamond ring", colorHex: "#e8d8b0", accentHex: "#1c1410", astronaut: "A GEO operator watches Bailey's beads from 36 000 km.", logline: "The only eclipse that lasts an hour." },
  { title: "Lunar Occult", family: "observatory", haleRef: "Hale Ch. 2", adaRef: "A_MOON", synopsis: "A radio source dies behind the limb.", colorName: "limb ash", colorHex: "#9a948c", accentHex: "#e8e2d8", astronaut: "A radio astronomer times a disappearance to the millisecond.", logline: "The Moon is a knife." },
  { title: "Earthshine EVA", family: "observatory", haleRef: "Hale Ch. 2", adaRef: "hale_orbital-constants.ads", synopsis: "Work lights off. Earth is enough.", colorName: "earthshine blue-grey", colorHex: "#6a7a88", accentHex: "#dce4ea", astronaut: "Two suits on a truss, lit only by a planet.", logline: "The Earth is a lamp." },
  { title: "Mars Sol", family: "interplanetary", haleRef: "Hale Ch. 8", adaRef: "earth_mars_mission.adb", synopsis: "24h 39m. A clock that drifts.", colorName: "sol rust", colorHex: "#b85c38", accentHex: "#f0d2b8", astronaut: "A crew resets their watches and never quite does.", logline: "A day and a bit." },
  { title: "Phobos Graze", family: "interplanetary", haleRef: "Hale two-body small moon", adaRef: "hale_orbital-twobody.adb", synopsis: "A moon so close it is a cliff.", colorName: "potato grey", colorHex: "#8a8078", accentHex: "#e8e0d4", astronaut: "A geologist almost touches Phobos with a boom.", logline: "Orbit is walking." },
  { title: "Deimos Quiet", family: "interplanetary", haleRef: "Hale two-body", adaRef: "hale_orbital-twobody.adb", synopsis: "The other moon. Almost not there.", colorName: "whisper grey", colorHex: "#a8a49c", accentHex: "#2a2824", astronaut: "A photographer waits for Deimos to be a star that moves.", logline: "Small is a mood." },
  { title: "Valles Fly", family: "interplanetary", haleRef: "Hale atmosphere", adaRef: "hale_orbital-interplanetary.adb", synopsis: "A canyon longer than a country, from 200 km.", colorName: "canyon red", colorHex: "#a33b32", accentHex: "#f0d4c4", astronaut: "A surveyor forgets the checklist for four seconds.", logline: "Geology at orbital speed." },
  { title: "Olympus Dawn", family: "interplanetary", haleRef: "Hale", adaRef: "hale_orbital-interplanetary.adb", synopsis: "A volcano that breaks the atmosphere's back.", colorName: "summit peach", colorHex: "#e09a6a", accentHex: "#2a1810", astronaut: "A meteorologist watches a cloud fail to cover the peak.", logline: "The mountain is a country." },
  { title: "Saturn Ring Graze", family: "interplanetary", haleRef: "Hale Ch. 8", adaRef: "hale_orbital-interplanetary.adb", synopsis: "A plane change measured in ice.", colorName: "ring champagne", colorHex: "#e8d4a8", accentHex: "#2a2418", astronaut: "A ring scientist holds her breath through the plane.", logline: "Thickness is a rumor." },
  { title: "Titan Orange", family: "interplanetary", haleRef: "Hale Ch. 8", adaRef: "hale_orbital-interplanetary.adb", synopsis: "A moon with weather. A probe with a parachute.", colorName: "tholin", colorHex: "#c46a32", accentHex: "#2a1408", astronaut: "A chemist hears the first wind noise from another world.", logline: "Rain that is not water." },
  { title: "Enceladus Jet", family: "interplanetary", haleRef: "Hale", adaRef: "hale_orbital-twobody.adb", synopsis: "A fly-through of a plume.", colorName: "jet white", colorHex: "#e8eef2", accentHex: "#1c2830", astronaut: "A biologist tastes the spectrograph and says nothing.", logline: "The ocean is spraying." },
  { title: "Pluto Terminator", family: "interplanetary", haleRef: "Hale two-body far", adaRef: "hale_orbital-twobody.adb", synopsis: "A heart-shaped ice and a long night.", colorName: "pluto heart", colorHex: "#c9a09a", accentHex: "#2a1818", astronaut: "A New Horizons veteran stands at a window that is a screen.", logline: "Nine years for one hour." },
  { title: "Voyager Geometry", family: "interplanetary", haleRef: "Hale Ch. 8 tour", adaRef: "hale_orbital-interplanetary.adb", synopsis: "The grand tour as a single drawing.", colorName: "gold record", colorHex: "#c9a44a", accentHex: "#2a220c", astronaut: "An old navigator traces four planets with one finger.", logline: "A once-in-176-years sentence." },
  { title: "Pale Blue", family: "observatory", haleRef: "Hale AU", adaRef: "AU constant", synopsis: "6.4 billion km. A pixel that is home.", colorName: "pale blue", colorHex: "#7a9ab0", accentHex: "#e8f0f4", astronaut: "Sagan's heirs dim the lights for the look back.", logline: "That is here. That is home." },
  { title: "Heliosphere Bow", family: "interplanetary", haleRef: "Hale energy", adaRef: "hale_orbital-twobody.adb", synopsis: "Where the solar wind remembers it is finite.", colorName: "bow shock", colorHex: "#6a7080", accentHex: "#d8dce8", astronaut: "A plasma physicist hears the termination whisper.", logline: "The Sun has a skin." },
  { title: "Oort Dark", family: "two-body", haleRef: "Hale two-body far", adaRef: "hale_orbital-twobody.adb", synopsis: "a so large the Sun is a bright star.", colorName: "coal", colorHex: "#2a2826", accentHex: "#c4b8a4", astronaut: "A comet-herder imagines a cloud she will never visit.", logline: "The reservoir." },
  { title: "Comet Whipple", family: "two-body", haleRef: "Hale Ch. 3 e~1", adaRef: "classifyOrbit", synopsis: "A dirty snowball on a long ellipse.", colorName: "coma milk", colorHex: "#d8d4c8", accentHex: "#2a2824", astronaut: "A night observer draws a tail that is not fire.", logline: "The tail is a wind sock." },
  { title: "Geminid Night", family: "observatory", haleRef: "Hale two-body small", adaRef: "hale_orbital-twobody.adb", synopsis: "A meteor stream as intersecting ellipses.", colorName: "meteor chalk", colorHex: "#e8e2d4", accentHex: "#2a2418", astronaut: "A child counts 43 and then falls asleep.", logline: "Orbits can be weather." },
  { title: "LEO Graveyard", family: "maneuver", haleRef: "Hale Ch. 6", adaRef: "Hohmann_Transfer", synopsis: "A raise to 300 km above GEO. The last burn.", colorName: "cemetery grey", colorHex: "#7a7874", accentHex: "#e8e4dc", astronaut: "A sat operator retires a bird and sits with it.", logline: "Even orbits end." },
  { title: "Starlink Sheet", family: "two-body", haleRef: "Hale Ch. 3", adaRef: "orbitalPeriod", synopsis: "A plane of many, as one organism.", colorName: "train white", colorHex: "#d8dce0", accentHex: "#2a3034", astronaut: "An astronomer waits six minutes for a gap.", logline: "A constellation is a choice." },
  { title: "OneWeb Weave", family: "two-body", haleRef: "Hale Ch. 3", adaRef: "orbitalPeriod", synopsis: "Another sheet, another inclination.", colorName: "weave silver", colorHex: "#b8c0c4", accentHex: "#1c2428", astronaut: "A spectrum manager draws two families and sighs.", logline: "The sky is zoned." },
  { title: "Hubble Breath", family: "observatory", haleRef: "Hale LEO", adaRef: "ISS_ALTITUDE", synopsis: "A 90-minute pointing against drag.", colorName: "mirror silver", colorHex: "#c8ccd0", accentHex: "#2a2c30", astronaut: "An observer holds lock while the Earth turns under the aperture.", logline: "LEO is a wind." },
  { title: "Chandra High", family: "observatory", haleRef: "Hale Ch. 3 eccentric", adaRef: "hale_orbital-elements.adb", synopsis: "A 64-hour ellipse. Most of the time far from Earth.", colorName: "x-ray violet-grey", colorHex: "#6a6578", accentHex: "#e4dce8", astronaut: "An X-ray astronomer loves apogee more than home.", logline: "Height is quiet." },
  { title: "XMM Long", family: "observatory", haleRef: "Hale Ch. 3", adaRef: "hale_orbital-elements.adb", synopsis: "Another high ellipse. European night.", colorName: "esoc blue-grey", colorHex: "#4a5c6a", accentHex: "#d4e0e8", astronaut: "A night shift in Darmstadt watches a 48-hour climb.", logline: "Apogee is the lab." },
  { title: "TESS Hunt", family: "cr3bp", haleRef: "Hale lunar resonance", adaRef: "hale_orbital-threebody.adb", synopsis: "A 13.7-day P/2 lunar resonant orbit.", colorName: "tess orange", colorHex: "#e07a3d", accentHex: "#2a1408", astronaut: "A planet-hunter sleeps in 13-day cycles.", logline: "The Moon is a partner." },
  { title: "Spektr-RG L2", family: "cr3bp", haleRef: "Hale Ch. 10 L2", adaRef: "Compute_Lagrange_Point L2", synopsis: "Another gold shield at Sun-Earth L2.", colorName: "survey gold", colorHex: "#c9a36b", accentHex: "#2a2418", astronaut: "Two telescopes, one saddle, two countries.", logline: "L2 is becoming a neighborhood." },
  { title: "Gaia Spin", family: "cr3bp", haleRef: "Hale Ch. 10 L2", adaRef: "Find_Halo_Orbit", synopsis: "A spinning mapper at L2. A billion stars.", colorName: "catalogue white", colorHex: "#e8e6e1", accentHex: "#4a4844", astronaut: "A cataloguer never looks at a single star. She looks at all of them.", logline: "The galaxy, measured." },
  { title: "Planck Cold", family: "cr3bp", haleRef: "Hale Ch. 10 L2", adaRef: "Find_Halo_Orbit", synopsis: "A 0.1 K instrument in a saddle.", colorName: "cmb cream", colorHex: "#e8dcc4", accentHex: "#2a2418", astronaut: "A cosmologist weeps at a map of the first light.", logline: "The oldest photograph." },
  { title: "Herschel Far", family: "cr3bp", haleRef: "Hale Ch. 10 L2", adaRef: "Find_Halo_Orbit", synopsis: "A 3.5 m far-IR dish that used its helium and died well.", colorName: "helium pale", colorHex: "#d4dce8", accentHex: "#243038", astronaut: "An operator watches the last Kelvin go.", logline: "Cold is a consumable." },
  { title: "DSCOVR Smile", family: "cr3bp", haleRef: "Hale Ch. 10 L1", adaRef: "Compute_Lagrange_Point L1", synopsis: "EPIC. The whole Earth, every two hours.", colorName: "epic blue", colorHex: "#3a6a9a", accentHex: "#d4e4f0", astronaut: "A climate lead pins a full-disk Earth to the wall.", logline: "L1 is a porch with a view." },
  { title: "ACE Wind", family: "cr3bp", haleRef: "Hale Ch. 10 L1", adaRef: "Compute_Lagrange_Point L1", synopsis: "Solar wind, an hour before it hits us.", colorName: "forewarning", colorHex: "#c49a4a", accentHex: "#2a220c", astronaut: "A grid operator gets an hour. She uses all of it.", logline: "L1 is a sentry." },
  { title: "WIND Craft", family: "cr3bp", haleRef: "Hale Ch. 10 L1", adaRef: "Propagate", synopsis: "A spacecraft that learned the manifolds by living them.", colorName: "old gold", colorHex: "#b0894a", accentHex: "#2a220c", astronaut: "A PI talks to a 30-year-old machine like a friend.", logline: "The orbits taught the book." },
  { title: "ARTEMIS Pair", family: "cr3bp", haleRef: "Hale Ch. 10 Earth-Moon", adaRef: "Earth_Moon_System", synopsis: "Two THEMIS probes given to the Moon.", colorName: "reassigned rust", colorHex: "#8c3b2a", accentHex: "#e8b59a", astronaut: "A magnetospherist watches Earth-Moon as one system.", logline: "Repurpose is a trajectory." },
  { title: "Queqiao", family: "cr3bp", haleRef: "Hale Ch. 10 EM L2", adaRef: "Find_Halo_Orbit L2", synopsis: "A relay so the far side can speak.", colorName: "jade night", colorHex: "#3d6b4f", accentHex: "#c8e6c0", astronaut: "A far-side rover driver hears the first word through a halo.", logline: "Without L2, silence." },
  { title: "CAPSTONE", family: "cr3bp", haleRef: "Hale Ch. 10 NRHO", adaRef: "Find_Halo_Orbit", synopsis: "A near-rectilinear halo. The Gateway's pathfinder.", colorName: "nrho bone", colorHex: "#cfc6b8", accentHex: "#3a3830", astronaut: "A navigator loves the long lunar pass and fears the close one.", logline: "Almost polar. Almost holy." },
  { title: "Gateway House", family: "cr3bp", haleRef: "Hale Ch. 10 NRHO", adaRef: "Find_Halo_Orbit", synopsis: "A house on a halo. Crew for 30 days.", colorName: "habitat warm", colorHex: "#c49a6a", accentHex: "#2a1c10", astronaut: "Someone tapes a photo of a kitchen to a bulkhead.", logline: "Home is a periodic orbit." },
  { title: "Lunar Ice Walk", family: "observatory", haleRef: "Hale geometry", adaRef: "A_MOON", synopsis: "Permanently shadowed. A walk with a lamp.", colorName: "psr black", colorHex: "#1a1816", accentHex: "#c4b8a4", astronaut: "A prospector kneels in a crater that has not seen the Sun in a billion years.", logline: "Ice is a coordinate." },
  { title: "Earthrise Again", family: "observatory", haleRef: "Hale Ch. 2", adaRef: "A_MOON", synopsis: "Borman's photograph, restaged from numbers.", colorName: "earthrise", colorHex: "#4a7a9a", accentHex: "#e8d4b0", astronaut: "A command-module pilot does not say what she is thinking.", logline: "The Earth comes up." },
];

function fillerBoard(
  colorName: string,
  colorHex: string,
  accentHex: string,
  astronaut: string,
  logline: string,
): Storyboard {
  return board(colorName, colorHex, accentHex, astronaut, logline, [
    { t: "0:00", shot: "The finding, written first.", camera: "insert of the number", fromFinding: "primary scalar" },
    { t: "0:40", shot: astronaut, camera: "human, then the sky", fromFinding: "the same number, lived" },
    { t: "2:00", shot: "The orbit as the camera understands it.", camera: "wide", fromFinding: "geometry" },
  ]);
}

export const CATALOG: Production[] = [];

for (const seed of SEEDS) {
  CATALOG.push({ id: CATALOG.length + 1, ...seed });
}
for (const row of MORE) {
  CATALOG.push({
    id: CATALOG.length + 1,
    slug: row.title.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/(^-|-$)/g, ""),
    title: row.title,
    family: row.family,
    haleRef: row.haleRef,
    adaRef: row.adaRef,
    synopsis: row.synopsis,
    runnable: false,
    shots: 10,
    targetMinutes: 3,
    storyboard: fillerBoard(row.colorName, row.colorHex, row.accentHex, row.astronaut, row.logline),
  });
}

if (CATALOG.length < 100) {
  const need = 100 - CATALOG.length;
  for (let i = 0; i < need; i++) {
    const n = CATALOG.length + 1;
    CATALOG.push({
      id: n,
      slug: `reserve-${String(n).padStart(3, "0")}`,
      title: `Reserve ${String(n).padStart(3, "0")}`,
      family: "cr3bp",
      haleRef: "Hale Ch. 10",
      adaRef: "hale_orbital-threebody.adb",
      synopsis: "Held for a later three-body film. Spec only.",
      runnable: false,
      shots: 8,
      targetMinutes: 3,
      storyboard: fillerBoard(
        "unexposed",
        "#6a6864",
        "#e8e4dc",
        "A director walks an empty soundstage and names a Lagrange point out loud.",
        "The slot exists. The sim does not, yet.",
      ),
    });
  }
}

export function productionById(id: number): Production | undefined {
  return CATALOG.find((p) => p.id === id);
}

export const FAMILY_LABEL: Record<ProductionFamily, string> = {
  "two-body": "two-body",
  maneuver: "maneuver",
  interplanetary: "interplanetary",
  lambert: "Lambert",
  cr3bp: "three-body",
  observatory: "observatory",
};
